### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by alexrili** [alexrili/simple-test#1]
# ToDo
- [x] Setup project
- [x] Intall AspectMock
- [x] Create a stubs generator
- [x] Response exceptions
- [x] Expose configs
  - [x] config stubs paths
  - [x] config aspect-mock paths
  - [x] show exception
